### PR TITLE
143 update feedback

### LINKED ISSUE #143: Update the feedback screen
Let's update the game feedback to be two parts: 

1. Feedback screen - Show participant's incorrect pairs in red (keep participant's English answers). There should be a 'next' button at the bottom that goes to the correct answer screen.
2. Correct answer screen - Show the correct word pairs. English words that the participant got incorrect will be outlined in green. There should be two buttons 'play again' and 'end session' at the bottom that behave like the current buttons.

When a user gets all words correct, then they are only shown the second screen (correct answer screen).

Specs:
- [ ] When a participant clicks 'done' on the game, they should be brought to the Feedback screen.
- [ ] When a participant clicks 'next' on the feedback screen, they should be brought to the Correct Answer screen.
- [ ] The tutorials for pairing and selecting game should be updated to match the new feedback screens (as shown below and on Figma).

[Updated feedback screens](https://www.figma.com/file/VF38OjNZyeKzf1pEenoyXu/Wirerframes-(Copy)?node-id=501%3A2)
Screen Shot 2022-03-23 at 7 26 27 PM

[Updated tutorials
](https://www.figma.com/file/VF38OjNZyeKzf1pEenoyXu/Wirerframes-(Copy)?node-id=501%3A2)
Screen Shot 2022-03-23 at 7 28 04 PM

### PR DESCRIPTION
**Pull request by Jake-Duffy855**
Closes #143

### CODE REVIEW

File: frontend/src/screens/GameScreen/gameScreen.tsx [hunk 1]
```diff
@@ -94,37 +96,70 @@ export default function GameScreen(props: SpecificGameScreenProps) {
...
-                    fi.endSession(sessionId);
-                    navigation.navigate("HomeScreen");
-                }} />
+          <PrimaryButton
+              disabled={isLoading}
+              onPress={() => {
+                  setIsLoading(true);
+                  restartRound();
+                  // setSubmitted(false);
+                  // setShowAnswers(false);
```
Comment (emaela) [inline frontend/src/screens/GameScreen/gameScreen.tsx]: Let's remove these lines of commented code

**Review by emaela — COMMENTED** [review]
So far it looks good, but I want to hold off on merging this because I anticipate changes to how the feedback screens are designed.

File: frontend/src/components/ResultRow.tsx [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+interface ResultRowProps {
+    turkish: string,
+    englishSelectingWord?: string,
+    english?: string,
+    correctEnglish: string,
+    showingAnswers: boolean, 
+    isPairing: boolean
+}
+
+export default function ResultRow({ turkish, englishSelectingWord, english, showingAnswers, correctEnglish, isPairing }: ResultRowProps) {
```
Comment (emaela) [inline frontend/src/components/ResultRow.tsx]: `englishSelectingWord` isn't used, shall we remove it?

File: frontend/src/components/ResultRow.tsx [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+    const correct = english === correctEnglish;
+    const unusedSelectingWord = (!english) && !isPairing;
+    
+    let extraTurkishInfo;
+    let extraEnglishInfo;
+    let extraContainerInfo;
```
Comment (emaela) [inline frontend/src/components/ResultRow.tsx]: Could we give these more descriptive names, possibly `additionalTurkishStyling` or something along those lines? Do let me know if I've misunderstood their purpose

File: frontend/src/components/CustomRow.tsx [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+    isPairing: boolean
+}
+
+export default function CustomRow({ turkish, englishSelectingWord, english, removeWord, wordDropped, showingResults, showingAnswers, correctEnglish, isPairing }: CustomRowProps) {
+    if (showingResults) {
+      return (<ResultRow
+        key={turkish}
+        showingAnswers={showingAnswers}
+        turkish={turkish}
+        showingResults={showingResults}
```
Comment (emaela) [inline frontend/src/components/CustomRow.tsx]: `showingResults` doesn't seem to be a necessary prop for `ResultRow` - if that's the case, let's remove it

File: frontend/src/screens/GameScreen/gameScreen.tsx [hunk 5]
```diff
@@ -130,38 +117,73 @@ export default function GameScreen(props: SpecificGameScreenProps) {
...
+                            removeWord={getRemoveWordHandler(currentPairs, word, i)}
+                            isPairing={props.isPairing}
+                    />))
+                )
+        }
     }
 
     const renderSubmittedButtons = () => {
+      if (showAnswers) {
         return (<View style={styles.doneContainer}>
```
Comment (emaela) [inline frontend/src/screens/GameScreen/gameScreen.tsx]: Can we put this `View` on a new line?

File: frontend/src/screens/GameScreen/gameScreen.tsx [hunk 6]
```diff
@@ -130,38 +117,73 @@ export default function GameScreen(props: SpecificGameScreenProps) {
...
                     fi.endSession(gameStateContext.sessionId);
                     gameStateContext.updateSessionId("");
                     gameStateContext.updateRoundId("");
                     navigation.navigate("HomeScreen");
-                }} />
-        </View>)
+              }} />
+      </View>)
+      } else {
+        return (<View style={styles.doneContainer}>
```
Comment (emaela) [inline frontend/src/screens/GameScreen/gameScreen.tsx]: Can we also put this `View` on a new line?

**Review by emaela — CHANGES_REQUESTED** [review]
Left some little comments, but otherwise LGTM!

**Comment by emaela** [comment]
@Octillerysnacker could you check that this looks good on android?
