### PR TITLE
Fixed cut-off of bottom of email verification screen on smaller screens

### LINKED ISSUE #97: Email verification screen is cut off for small screens
Let's make the email verification screen responsive  so that it also works for small screens. Below is an image of how it currently looks for small screens, versus how [it was intended to look](https://github.com/sandboxnu/flow-in-the-field/pull/91):
IMG_B95DF8A28781-1

### PR DESCRIPTION
**Pull request by ShashJar**
closes #97

### CODE REVIEW

**Review by emaela — CHANGES_REQUESTED** [review]
This is a nitpick, but could we make its so that the error message appears above the button without pushing it downwards?

IMG_4145

**Comment by ShashJar** [comment]
fixed!

File: frontend/src/screens/emailVerificationScreen.tsx [hunk 1]
```diff
@@ -69,13 +69,14 @@ const styles = StyleSheet.create({
...
         width: "100%",
+        height: "87%",
         alignItems: "center"
     },
 
     mainImage: {
         width: "60%",
         resizeMode: 'contain',
-        maxHeight: 158,
+        maxHeight: "26.4%",
```
Comment (emaela) [inline frontend/src/screens/emailVerificationScreen.tsx:79]: What are your thoughts on making these nice numbers, like 85, 25, and 2%? I don't think it would make too much of a difference visually, but I think it would be neater to not have decimals here.

Otherwise, it looks good!

**Review by emaela — APPROVED** [review]
Aside from the percentages, this looks good to merge!

**Review by emaela — APPROVED** [review]
Aside from the percentages, this looks good to merge!
